version: "2"

services:
  postgres:
    image: postgres:13.2
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    expose:
      - 5432
    environment:
      POSTGRES_USER: opensanctions
      POSTGRES_PASSWORD: opensanctions

  worker:
    build: .
    command: bash -c -i "
        rm -rf ../data/datasets
        && rm -rf ../data/cache
        && opensanctions run un_sc_sanctions
        && mkdir -p ../data/export
        && ftm export-excel -i ../data/datasets/un_sc_sanctions/entities.ftm.json -o ../data/export/un_sc_sanctions.xlsx
        "
    links:
      - postgres
    volumes:
      - "./data/data:/data"
      - "./opensanctions:/opensanctions/opensanctions"
    tmpfs:
      - "/tmp"
    environment:
      OPENSANCTIONS_DATABASE_URI: postgresql://opensanctions:opensanctions@postgres/opensanctions
